// Featured-image picker source list. Per spec, this reuses the existing
// public/img/ asset folder rather than adding upload/storage infrastructure —
// kept as a plain list (Vite's import.meta.glob doesn't resolve the public/
// directory the same way it does src/) so it needs a manual refresh if new
// images are added to public/img/ outside the admin panel.
export const AVAILABLE_IMAGES: string[] = [
  'img/Battery-Electrical.jpg',
  'img/Car-Diagnostics.jpg',
  'img/Car-Wash-detailing.jpg',
  'img/Car-ac-Service.jpg',
  'img/Cooling-System-Service.jpg',
  'img/Emergency-Roadside-Assistance.jpg',
  'img/Expert-Technicians.jpg',
  'img/Periodic-Maintenance.jpg',
  'img/Suspension-Steering.jpg',
  'img/Trusted-Service.jpg',
  'img/about-1.jpg',
  'img/advanced-tools.jpg',
  'img/body-repiaring.jpg',
  'img/brake-service.jpg',
  'img/car-full-service.jpg',
  'img/car-hybrid-battery.jpg',
  'img/car-parts.jpg',
  'img/car-servicing.jpg',
  'img/car-technician.jpg',
  'img/car-wash.jpg',
  'img/engine-oil-filter.jpg',
  'img/engine-repeir.jpg',
  'img/evn-1.jpg',
  'img/evn-2.jpg',
  'img/evn-3.jpg',
  'img/evn-4.jpg',
  'img/expert-advice.jpg',
  'img/expert-technitian.jpg',
  'img/hybrid-battery-diagnostics.jpg',
  'img/hybrid-battery-replacement.jpg',
  'img/hybrid-car-motor.jpg',
  'img/hybrid-car.jpg',
  'img/hybrid-ecu-scanning.jpg',
  'img/latest-1.jpg',
  'img/latest-2.jpg',
  'img/latest-3.jpg',
  'img/latest-4.jpg',
  'img/latest-5.jpg',
  'img/latest-6.jpg',
  'img/lpg-and-cng.jpg',
  'img/lpg.jpg',
  'img/oil-and-filter.jpg',
  'img/regenerative-brake-service.jpg',
  'img/transmission-service.jpg',
  'img/trusted-service-2.jpg',
  'img/tyre-service.jpg',
  'img/wheel-alignment.jpg',
];
